- hosts: all
  debugger: on_failed
  gather_facts: false

  tasks:
    - name: Wait until the instance is ready
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Artifactory repository added
      become: true
      ansible.builtin.yum_repository:
        name: artifactory-pro-rpms
        description: artifactory Pro
        baseurl: https://releases.jfrog.io/artifactory/artifactory-pro-rpms/

    - name: Artifactory Pro installed
      become: true
      ansible.builtin.dnf:
        name: jfrog-artifactory-pro
        update_cache: true
        disable_gpg_check: true
        state: present

    - name: Artifactory service is enabled and running
      become: true
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: artifactory

    - name: Make sure artifactory is up and running
      uri:
        url: http://{{inventory_hostname}}:8082/router/api/v1/system/health
        timeout: 130
        status_code: 200
      register: result
      until: result is succeeded
      retries: 25
      delay: 5
